=== GermanDiazGlez/validaciones/xml/concesionarios.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="concesionarios">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="concesionario" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="concesionario">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre" />
        <xs:element ref="marca" />
        <xs:element ref="numeroVehiculos" />
        <xs:element ref="ubicacion" />
        <xs:element ref="imagen" />
        <xs:element ref="empleados" />
        <xs:element ref="direccion" />
      </xs:sequence>
      <xs:attribute name="tipo-vehiculo" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="Deportivo" />
            <xs:enumeration value="Todoterreno" />
            <xs:enumeration value="Electrico" />
            <xs:enumeration value="SUV" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre" type="xs:string" />
  <xs:element name="marca" type="xs:string" />
  <xs:element name="numeroVehiculos" type="xs:decimal" />
  <xs:element name="ubicacion">
    <xs:complexType>
      <xs:attribute name="lat" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:float">
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="lng" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:float">
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="imagen">
    <xs:complexType>
      <xs:attribute name="src" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="title" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="alt" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="empleados">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="empleado" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="empleado">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nombre-empleado" />
        <xs:element ref="apellidos" />
        <xs:element ref="telefono" />
      </xs:sequence>
      <xs:attribute name="puesto" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="Ventas" />
            <xs:enumeration value="Oficina" />
            <xs:enumeration value="Asesor" />
            <xs:enumeration value="Director" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="nombre-empleado" type="xs:string" />
  <xs:element name="apellidos" type="xs:string" />
  <xs:element name="telefono" type="xs:decimal" />
  <xs:element name="direccion" type="xs:string" />
</xs:schema>

=== GermanDiazGlez/validaciones/xml/concesionarios.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE concesionarios [
<!ELEMENT concesionarios (concesionario+)>
<!ELEMENT concesionario (nombre, marca, numeroVehiculos, ubicacion, imagen, empleados, direccion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT numeroVehiculos (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT empleados (empleado+)>
<!ELEMENT empleado (nombre-empleado, apellidos, telefono)>
<!ELEMENT nombre-empleado (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ATTLIST concesionarios xmlns:xsi CDATA #REQUIRED>
<!ATTLIST concesionarios xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
<!ATTLIST concesionario tipo-vehiculo CDATA #REQUIRED>
<!ATTLIST ubicacion 
    lat CDATA #REQUIRED
    lng CDATA #REQUIRED>
<!ATTLIST imagen 
    src CDATA #REQUIRED
    title CDATA #REQUIRED
    alt CDATA #REQUIRED>
<!ATTLIST empleado puesto CDATA #REQUIRED>
]>

<concesionarios xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='./concesionarios.xsd'>
    <concesionario tipo-vehiculo="Deportivo">
        <nombre>Varocar</nombre>
        <marca>Seat</marca>
        <numeroVehiculos>38</numeroVehiculos>
        <ubicacion lat="43.31147423748632" lng="-5.695053703377107"></ubicacion>
        <imagen src="varocar.jpg" title="VarocarFoto" alt="Concesionario Varocar"></imagen>
        <empleados>
            <empleado puesto="Ventas">
                <nombre-empleado>Juan</nombre-empleado>
                <apellidos>Mendez Rodriguez</apellidos>
                <telefono>621655521</telefono>
            </empleado>
            <empleado puesto="Ventas">
                <nombre-empleado>Elena</nombre-empleado>
                <apellidos>Lopez Rodriguez</apellidos>
                <telefono>691654551</telefono>
            </empleado>
        </empleados>
        <direccion>Calle La Traba La Felguera Asturias España</direccion>
    </concesionario>
    <concesionario tipo-vehiculo="Deportivo">
        <nombre>Tartiere Auto</nombre>
        <marca>Volkswagen</marca>
        <numeroVehiculos>43</numeroVehiculos>
        <ubicacion lat="43.40694059256487" lng="-5.804820702131801"></ubicacion>
        <imagen src="tartiere.jpg" title="TartiereFoto" alt="Concesionario Tartiere"></imagen>
        <empleados>
            <empleado puesto="Ventas">
                <nombre-empleado>Enrique</nombre-empleado>
                <apellidos>Gonzalez Gonzalez</apellidos>
                <telefono>641655632</telefono>
            </empleado>
            <empleado puesto="Oficina">
                <nombre-empleado>Marta</nombre-empleado>
                <apellidos>Gonzalez Gonzalez</apellidos>
                <telefono>671655332</telefono>
            </empleado>
        </empleados>
        <direccion>Calle Avenida de Gijon Lugones Asturias España</direccion>
    </concesionario>
    <concesionario tipo-vehiculo="Todoterreno">
        <nombre>Mitsubishi Cisacar</nombre>
        <marca>Mitsubishi</marca>
        <numeroVehiculos>20</numeroVehiculos>
        <ubicacion lat="43.39239186388887" lng="-5.79372357870682"></ubicacion>
        <imagen src="mitsubishi.jpg" title="MitsubishiFoto" alt="Concesionario Mitsubishi"></imagen>
        <empleados>
            <empleado puesto="Ventas">
                <nombre-empleado>Antonio</nombre-empleado>
                <apellidos>Sanchez Garcia</apellidos>
                <telefono>641655886</telefono>
            </empleado>
            <empleado puesto="Asesor">
                <nombre-empleado>Laura</nombre-empleado>
                <apellidos>Perez Martínez</apellidos>
                <telefono>666655886</telefono>
            </empleado>
            <empleado puesto="Director">
                <nombre-empleado>Claudia</nombre-empleado>
                <apellidos>Gomez Bermejo</apellidos>
                <telefono>676262886</telefono>
            </empleado>
        </empleados>
        <direccion>Calle Aldea de Paredes Parque Principado Lugones Asturias España</direccion>
    </concesionario>
    <concesionario tipo-vehiculo="Deportivo">
        <nombre>Autos Myr</nombre>
        <marca>Seat</marca>
        <numeroVehiculos>13</numeroVehiculos>
        <ubicacion lat="43.34534701651665" lng="-5.852967484443624"></ubicacion>
        <imagen src="myr.jpg" title="MyrFoto" alt="Concesionario Myr"></imagen>
        <empleados>
            <empleado puesto="Ventas">
                <nombre-empleado>Juan José</nombre-empleado>
                <apellidos>Soler Gonzalez</apellidos>
                <telefono>649995632</telefono>
            </empleado>
        </empleados>
        <direccion>Calle José García Nieto Lugones Asturias España</direccion>
    </concesionario>
</concesionarios>
